### PR TITLE
Carlos Test Creation & Organization

### PR DESCRIPTION
**Pull request by solarescarlos**
- Created test files for each of the backend python files.
- Organized backend files into a better structure
- Implemented create_prediction_data() in read_data.py (Eric please check this out)

### CODE REVIEW

**Review by Adventurer-E — COMMENTED** [review]
1. I wouldn't recommend to write "from **backend**.Model import something" cuz we shouldn't do this. I doubt there were issues with CI/CD and have asked Alex and Tara. For now, I would suggest trying to use absolute path.
See my conversation with ChatGPT for more instructions:
https://chatgpt.com/share/6725bb6b-e600-8011-9a99-c14104e38493
2. For create_prediction_data, I don't think we should implement the filtering logic at this stage. Could you add a new file and implement the filtering logic? I think for read_data, its only job is to call functions from elsewhere [let's discuss with Matthew on this later].

**Comment by Adventurer-E** [comment]
Screenshot 2024-11-02 at 2 46 48 AM

This is what I think create_prediction_data should look like: the role of read_data is just calling the methods and transfer them to app.py. It doesn't do filtering by itself. Could you please write a filter function in a new file? The new filtwer function should input spefici "filters" (such as sex, race, etc) and output the data already filtered. My design idea is that the model is re-run for each filter as the "original dataset" is different under each filter. Here's my modified read_data.py:
`import pandas as pd
import os
from Model import TARGET_VAR, Model

# Read the raw dataset from the csv
def read_dataset():
    # Temporary
    # return {"data": "yes"}
    return pd.read_csv(os.path.join(os.path.dirname(__file__), "data", "transaction_data.csv"))

def create_model(filter):
    raw_data = read_dataset()
    # filtered_data = filter(raw_data, filtering_factor)  # to be checked with Carlos
    filtered_data = raw_data  # temporary
    return Model(filtered_data)

# Creates the data in the format that VISX needs
def create_formatted_data(filter):
    cleaned_data = create_model(filter).get_cleaned_data()
    formatted_data = [
        {'date': record['Date'].strftime('%Y-%m-%d'), 'value': record[TARGET_VAR]}
        for record in cleaned_data[['Date', TARGET_VAR]].drop_duplicates().to_dict(orient='records')
    ]
    return formatted_data

def create_prediction_data(filter, forecast_steps: int):
    model = create_model(filter)
    forecast_df = model.get_forecast()
    forecast_values = forecast_df['mean']
    future_dates = pd.date_range(start=model.get_cleaned_data().index[-1] + pd.DateOffset(months=0), periods=forecast_steps, freq='D')
    prediction_unformatted =  [{'date': date, 'value': value}
                        for date, value in zip(future_dates, forecast_values)]
    prediction_data = [{'date': record['date'].strftime('%Y-%m-%d'), 'value': int(record['value'])} for record in prediction_unformatted]
    return prediction_data

print(create_formatted_data('A'))`

If you have a different design idea plz lmk.
Also, I'll push my changes **after** you implement the filter, so when you complete implementing the filter plz also lmk.

**Comment by BardyBard** [comment]
> 1. I wouldn't recommend to write "from **backend**.Model import something" cuz we shouldn't do this. 

I also remember seeing something about it being not recommended. However, Carlos has already made the __init__.py files to turn all our folders into packages, so just adding the `backend.*` now works from anywhere within our python environment (*I believe). If you just test it out locally after adding the `backend.` imports  everything works so I don't see it as a big issue.

> For now, I would suggest trying to use absolute path.
>    See my conversation with ChatGPT for more instructions:
>    https://chatgpt.com/share/6725bb6b-e600-8011-9a99-c14104e38493

If you think absolute path is a more futureproof implementation then sounds good. Matthew and I tried to get it to work a couple days ago when we were having the Heroku issues and it didnt seem to work.

**Comment by BardyBard** [comment]
Also this really should be split into two PR's one about the model changes and one about the backend/backend_test changes

**Comment by MatthewFrieri** [comment]
We should decide on one way of doing these imports that we can keep consistent for the entire backend.

I don't think I understand fully what's happening in create_prediction_data(). Maybe you can explain it tdy on call.

Also the backend build is failing from import statements.

**Comment by solarescarlos** [comment]
> 1. I wouldn't recommend to write "from **backend**.Model import something" cuz we shouldn't do this. I doubt there were issues with CI/CD and have asked Alex and Tara. For now, I would suggest trying to use absolute path.
>    See my conversation with ChatGPT for more instructions:
>    https://chatgpt.com/share/6725bb6b-e600-8011-9a99-c14104e38493
I also had a long chat with GPT last night about this whole import mess. Still trying to figure it out. I attempted using an absolute path but it still wasn't quite working. I'm debating just returning the file organization to how it was before. 

> 2. For create_prediction_data, I don't think we should implement the filtering logic at this stage. Could you add a new file and implement the filtering logic? I think for read_data, its only job is to call functions from elsewhere [let's discuss with Matthew on this later].
@Adventurer-E The reason I implemented the filter function in read_data was because that file also contains a function to read the dataset and another to format it, so it seemed logical that a function to filter data (which is also basically formatting it) would also go here. It would be great if you could hop on a call later today to discuss each of these files (app, Model, read_data) because it is unclear to me what each file is supposed to contain/do. I disagree that we should create a separate file for the data filtering, after all it's not a huge function. It should exist in whatever file we assign to data manipulation/formatting (whether that be read_data or something else). The reason I implemented it in create_prediction_data was because of how I interpreted the comments on the file. I see what you want to do with that function now, and it looks good. Maybe create_prediction_data should be in a file on its own though (let's talk about this today).

**Review by BardyBard — APPROVED** [review]
Nice

**Review by Adventurer-E — APPROVED** [review]

**Pull request merged**
