### PR TITLE
heather-and-tara- desktop-navigation

### PR DESCRIPTION
**Pull request by taheat04**
Resolved merge conflict and add a navigation from login to the main page

### CODE REVIEW

**Review by MatthewFrieri — CHANGES_REQUESTED** [review]
theres tons of files that you guys included in the commits that shouldn't be in here:

.anima folder
nodemodules folder
package.json
package-lock.json

this is probably because you npm installed modules when you weren't in the frontend directory

**Comment by avantitandon** [comment]
Sorry, those were lib

> theres tons of files that you guys included in the commits that shouldn't be in here:
> 
> .anima folder nodemodules folder package.json package-lock.json
> 
> this is probably because you npm installed modules when you weren't in the frontend directory

sorry those were libraries I had installed trying to make the figma plugin work but I ended up doing it from scratch, forgot to remove it

**Comment by taheat04** [comment]
The tests were passed locally but it's not working here ill figure it out later after talking with Matt

**Review by MatthewFrieri — APPROVED** [review]
W

**Review by solarescarlos — APPROVED** [review]

**Pull request merged**
