### PR TITLE
Eric filter enhancement

### PR DESCRIPTION
**Pull request by Adventurer-E**
Screenshot 2024-11-12 at 2 11 50 PM

Note that although both dropdown menus are implemented on the frontend, only gender_filter is available on the backend currently. I'll make further changes when app.py is modified to accept both filtering factors.
For now, if you pick a race, the graph will automatically return to the no-filter state, no matter what value is in "Gender".

### CODE REVIEW

**Review by avantitandon — APPROVED** [review]
Co

**Review by BardyBard — DISMISSED** [review]
The race filter and gender filter should update different variables, filter_race and filter_gender respectively. I believe it would be better and cleaner if we did it through a dictionary. So pass through an empty dictionary filters = {} when there are no selected filters, or you can pass through filters = {race_filter = None, gender_filter = None), up to you which one you think is easier/better when there are no selected filters. 

And when a filter is selected pass through a dictionary like filters = { race_filter: "Asian", gender_filter: "woman"}

**Comment by Adventurer-E** [comment]
> The race filter and gender filter should update different variables, filter_race and filter_gender respectively. I believe it would be better and cleaner if we did it through a dictionary. So pass through an empty dictionary filters = {} when there are no selected filters, or you can pass through filters = {race_filter = None, gender_filter = None), up to you which one you think is easier/better when there are no selected filters.
> 
> And when a filter is selected pass through a dictionary like filters = { race_filter: "Asian", gender_filter: "woman"}

I'll make this change after the corresponding backend is implemented (or at least a fake hardcode).

**Comment by BardyBard** [comment]
> I'll make this change after the corresponding backend is implemented (or at least a fake hardcode).

The backend is implemented, if you look at DataFormatter.filter_by, it has many available filter_type inputs

**Comment by Adventurer-E** [comment]
For now, both filter works. When both filters are applied (especially the race filter), the prediction data may not be available. This issue is brought by the discontinuity of the pastData after applying filter. I'll create a new ticket for this.

**Review by MatthewFrieri — APPROVED** [review]

**Pull request merged**
