### PR TITLE
Heather mainpage UI plus simple illustration how to read graph

### PR DESCRIPTION
**Pull request by taheat04**
Dont merge yet. I need some feedback plzz

image

### CODE REVIEW

**Comment by avantitandon** [comment]
wait I really love this, I'm making a few changes to the text tho

**Comment by Adventurer-E** [comment]
I would suggest to make the bar above narrower and put everything in one screen without scrolling.
Screenshot 2024-11-24 at 9 07 18 PM

**Comment by Adventurer-E** [comment]
Looks pretty nice! It would be better if everything is on a single screen without scrolling. Maybe can realize this by narrowing the navbar.

**Review by Adventurer-E — APPROVED** [review]

**Review by avantitandon — APPROVED** [review]
adding more changes on a different pr else this will be bloated

**Pull request merged**
