### PR TITLE
refactored_filter

### PR DESCRIPTION
**Pull request by avantitandon**
Haven't fixed the try-except. Created a class so we can keep adding filters.

### CODE REVIEW

**Review by MatthewFrieri — CHANGES_REQUESTED** [review]
instead of using a try and except inside read_data you can check if its a number with filtering_factor.isnumeric()

also, there should only be logic like if statements in the classes (use casses?) themselves. so im pretty sure you can have another abstract method in Filter to determine if the filtering_factor is refering to that filter subclass. then maybe you can use polymorphism to check all the filters to see which is the right one

**Review by BardyBard — CHANGES_REQUESTED** [review]
1. This is two pull requests in one, its hard to discuss the two at once, can you please only make this pull request the filtering object one, as you already have a separate pull request for the upload feature. 

2. The whole point of rewriting filtering factor was to now have a "filter_age" "filter_gender" "filter_race" variable. Please read the ticket desciption before starting a task, especially since Carlos wanted to do this task. 
 
3. Building separate filtering variables will solve the age_filter try expect error as it will only expect an intiger as an input.
 
4. Lastly, an OOP structure of the filters would have an abstract filter that would be implemented by the specific filter types. So can you also please include that. 
 
5. Lastly, lastly, for now we are only focusing on the gender filter as it is the only one crucial for our MVP, if you want to you can also try to fix the other filters to this specification but there are higher priority tasks as well that we could be working on.

**Comment by avantitandon** [comment]
> 1. This is two pull requests in one, its hard to discuss the two at once, can you please only make this pull request the filtering object one, as you already have a separate pull request for the upload feature.
> 2. The whole point of rewriting filtering factor was to now have a "filter_age" "filter_gender" "filter_race" variable. Please read the ticket desciption before starting a task, especially since Carlos wanted to do this task.
> 3. Building separate filtering variables will solve the age_filter try expect error as it will only expect an intiger as an input.
> 4. Lastly, an OOP structure of the filters would have an abstract filter that would be implemented by the specific filter types. Like matthew mentioned above.
> 5. Lastly, lastly, for now we are only focusing on the gender filter as it is the only one crucial for our MVP, if you want to you can also try to fix the other filters to this specification but there are higher priority tasks as well that we could be working on.

I had earlier made a branch to incorporate the filter_age, filter_gender and filter race variables but it requires changing create dataset and the logic for the flask endpoints, and frankly an unnecessary amount of parameters that we would have to keep making if there are more variables we are filtering, whereas this logic takes whatever sub filter we are using and keeps the only variable we need "filtering_factor". I incorporated Matthews changes removing the try except and moving the logic in a file manager class, which can be updated depending on what else we're filtering with. 
(However If the group wants to do it the first way, totally cool I can publish that branch and we can work on it)
Secondly, if you look at the file filters.py you would see that it has OOP structure with the with the abstract filter method and the separate classes implementing it. 
Thirdly, sorry about the multiple pull requests, I worked on the pr branch thinking it had been merged already, though I don't think it changes much anyways.

**Review by BardyBard — APPROVED** [review]
Looks good, concerned about the state filter but we won't be using it for now.

**Review by BardyBard — APPROVED** [review]

**Review by MatthewFrieri — APPROVED** [review]

**Pull request merged**
