### PR TITLE
Eric enable mode change

### PR DESCRIPTION
**Pull request by Adventurer-E**
Enabled change between number of transaction and value of transaction by radiobutton at the top of the page.
Screenshot 2024-11-12 at 9 39 25 PM
Screenshot 2024-11-12 at 9 39 31 PM

### CODE REVIEW

**Review by BardyBard — COMMENTED** [review]
I don't think renaming the frequency, and revenue columns back to value and value is good practice, what do others think?

(Also approve my renaming pr before this if we want to keep the specific names instead of value, because I initially called it num_transactions which is a much shittier name than frequency)

**Comment by Adventurer-E** [comment]
> I don't think renaming the frequency, and revenue columns back to value and value is good practice, what do others think?
> 
> (Also approve my renaming pr before this if we want to keep the specific names instead of value, because I initially called it num_transactions which is a much shittier name than frequency)

Sure, I've reversed the changes and also updated num_transactions to frequency.

**Review by BardyBard — APPROVED** [review]
Very very nice, appreciate you renaming the column names.

**Review by solarescarlos — APPROVED** [review]
Lgtm

**Pull request merged**
